# Generated by Django 5.0 on 2023-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='category',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Cars', 'Cars'), ('Drinks', 'Drinks'), ('E-Commerce', 'E-Commerce'), ('Fashion', 'Fashion'), ('Financial', 'Financial'), ('Food', 'Food'), ('Industrial', 'Industrial'), ('Internet', 'Internet'), ('Media', 'Media'), ('Soccer', 'Soccer'), ('Technology', 'Technology')], default='none', max_length=25),
            preserve_default=False,
        ),
    ]
