# Generated by Django 5.0 on 2023-12-24 08:43

from django.db import migrations, models 

def loadData(apps, schema_editor):
		from django.core.management import call_command
		call_command("loaddata", "Logo")

def deleteData(apps, schema_editor):
		model = apps.get_model("api", "Logo")
		model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logo_category'),
    ]

    operations = [
		migrations.RunPython(loadData, deleteData)
    ]
